/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chiaj
 */
public class Register extends javax.swing.JFrame
{

    private int row = -1;
    
    private DefaultTableModel model = new DefaultTableModel();
    
    private String[] column = {"Name", "ID", "Password"};



    public Register()
    {
        initComponents();
        
        setLocationRelativeTo(null) ;
        
        model.setColumnIdentifiers(column);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        RFLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTFNameRegister = new javax.swing.JTextField();
        JBRegisterUser = new javax.swing.JButton();
        jBDeleteUser = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        JTFIDReg = new javax.swing.JTextField();
        JBUpdateUser = new javax.swing.JButton();
        JBShowUser = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        JTFPasswordReg = new javax.swing.JTextField();
        JBsave = new javax.swing.JButton();
        JBClearUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTPasswordTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        RFLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        RFLabel.setForeground(new java.awt.Color(0, 0, 0));
        RFLabel.setText("Registration Form");
        jPanel1.add(RFLabel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name:");
        jPanel4.add(jLabel1);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));

        jTFNameRegister.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTFNameRegisterActionPerformed(evt);
            }
        });

        JBRegisterUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        JBRegisterUser.setText("Register User");
        JBRegisterUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JBRegisterUserActionPerformed(evt);
            }
        });

        jBDeleteUser.setText("delete user");
        jBDeleteUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTFNameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(JBRegisterUser)
                .addGap(18, 18, 18)
                .addComponent(jBDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNameRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBRegisterUser)
                    .addComponent(jBDeleteUser))
                .addGap(22, 22, 22))
        );

        jPanel2.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(153, 255, 255));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID:");
        jPanel7.add(jLabel2);

        jPanel2.add(jPanel7);

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));

        JTFIDReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JTFIDRegActionPerformed(evt);
            }
        });

        JBUpdateUser.setText("update user");
        JBUpdateUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JBUpdateUserActionPerformed(evt);
            }
        });

        JBShowUser.setText("show User");
        JBShowUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JBShowUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(JTFIDReg, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(JBUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBShowUser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFIDReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBUpdateUser)
                    .addComponent(JBShowUser))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(153, 255, 255));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password:");
        jPanel8.add(jLabel3);

        jPanel2.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));

        JTFPasswordReg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JTFPasswordRegActionPerformed(evt);
            }
        });

        JBsave.setText("save");
        JBsave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JBsaveActionPerformed(evt);
            }
        });

        JBClearUser.setText("Clear");
        JBClearUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JBClearUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(JTFPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(JBsave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBClearUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBsave)
                    .addComponent(JBClearUser))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(153, 255, 255));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        JTPasswordTable.setModel(model);
        JTPasswordTable.addMouseListener(new java.awt.event.MouseAdapter()
            {
                public void mouseReleased(java.awt.event.MouseEvent evt)
                {
                    JTPasswordTableMouseReleased(evt);
                }
            });
            jScrollPane1.setViewportView(JTPasswordTable);

            jPanel11.add(jScrollPane1);

            jPanel3.add(jPanel11, java.awt.BorderLayout.PAGE_START);

            getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    public void clearTextField()
    {
        jTFNameRegister.setText("");
         
        JTFIDReg.setText(""); 
        
        JTFPasswordReg.setText("");
    }
    
    public void WriteFiles(String files,boolean m)
    {
         try
        {
           FileWriter fw = new FileWriter(files, m);
            
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i= 0; i<JTPasswordTable.getRowCount(); i++)//rows
            {
                  
                for(int j =0; j<JTPasswordTable.getColumnCount();j++)
                {
                    
                    bw.write(JTPasswordTable.getValueAt(i, j).toString()+", ");
                
                
                      
                }
                bw.newLine();
            }
            
            
            bw.close();
            fw.close();
            
        } 
        catch (IOException ex)
        {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void ReadFiles(String l)
    {
        
      FileReader fr = null;
       
        try
        {
            fr = new FileReader(l);
           BufferedReader br = new BufferedReader(fr);
           
           DefaultTableModel model2 =(DefaultTableModel)JTPasswordTable.getModel();
           
           Object[] lines = br.lines().toArray();
           
           for(int i =0; i<lines.length;i++)
           {
               String[] row=lines[i].toString().split(" ");
              
                  // Replace commas with an empty string in each element of the row
            for (int j = 0; j < row.length; j++) {
                row[j] = row[j].replace(",", "");
            }
               
               
                
               model.addRow(row);
           }
        } 
        
        catch (FileNotFoundException ex)
        {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     
        
    }
    
    private void jTFNameRegisterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTFNameRegisterActionPerformed
    {//GEN-HEADEREND:event_jTFNameRegisterActionPerformed
        
    }//GEN-LAST:event_jTFNameRegisterActionPerformed

    private void JTFIDRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JTFIDRegActionPerformed
    {//GEN-HEADEREND:event_JTFIDRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFIDRegActionPerformed

    private void JTFPasswordRegActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JTFPasswordRegActionPerformed
    {//GEN-HEADEREND:event_JTFPasswordRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPasswordRegActionPerformed

    private void JBRegisterUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JBRegisterUserActionPerformed
    {//GEN-HEADEREND:event_JBRegisterUserActionPerformed
        String name = jTFNameRegister.getText();

        String ID = JTFIDReg.getText();

        String password = JTFPasswordReg.getText();
       if(name.contains(",")||ID.contains(",")||password.contains(","))
       {
           JOptionPane.showMessageDialog(this, "Please avoid using commas in your input!");
       }
      else if( ID.length() == 0 || name.length() == 0|| ID.length() == 0|| password.length() == 0)
      {
          JOptionPane.showMessageDialog(this,"Pleae fill up the form!");
      }
      else
      {
          String []value = {name,ID,password}; 
          model.addRow(value);
          clearTextField();
      }
        
        
    
        
     
    
    }//GEN-LAST:event_JBRegisterUserActionPerformed

    private void JTPasswordTableMouseReleased(java.awt.event.MouseEvent evt)                                      
    {                                          
      
      row= JTPasswordTable.getSelectedRow();
        
     
      String Name = String.valueOf(model.getValueAt(row, 0));
      
      String id = String.valueOf(model.getValueAt(row, 1));
       
       
      String Address = String.valueOf(model.getValueAt(row, 2));
       
      
     
        jTFNameRegister.setText(id);
         
        JTFIDReg.setText(id); 
        
        JTFPasswordReg.setText(Name);
  
      
    } 
    
    private void JBUpdateUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JBUpdateUserActionPerformed
    {//GEN-HEADEREND:event_JBUpdateUserActionPerformed
            if(row == -1)
            {
                JOptionPane.showMessageDialog(this, "Please select a row to delete!");
            }
             else{
                    String name =  jTFNameRegister.getText();
       
                    String id = JTFIDReg.getText();
       
                    String password =  JTFPasswordReg.getText();
       
                     model.setValueAt(name, row, 0);
                        
                     model.setValueAt(id, row, 1);
      
                     model.setValueAt(password, row, 2);
  
                     model.removeRow(row);
      
     
                     String[] value = {name,id, password};
       
      
                     model.insertRow(row, value);
      
      
                     clearTextField();
      
     
                     row = -1; 
                } 
            
            
            
               WriteFiles("C:\\Users\\chiaj\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\password.txt",false);
         
               WriteFiles("C:\\Users\\chiaj\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\credit.txt",false);
         
         
   
    }//GEN-LAST:event_JBUpdateUserActionPerformed

    private void jBDeleteUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBDeleteUserActionPerformed
    {//GEN-HEADEREND:event_jBDeleteUserActionPerformed
          if(row == -1)
        {
            JOptionPane.showMessageDialog(this, "Please select a row to delete!");
        }
        else{
         model.removeRow(row);
        
         clearTextField();
         
         row = -1;
         
        }
          
         WriteFiles("C:\\Users\\chiaj\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\password.txt",false);
         
          WriteFiles("C:\\Users\\chiaj\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\credit.txt",false);
   
    }//GEN-LAST:event_jBDeleteUserActionPerformed

    private void JBShowUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JBShowUserActionPerformed
    {//GEN-HEADEREND:event_JBShowUserActionPerformed
        DefaultTableModel model4 = (DefaultTableModel) JTPasswordTable.getModel();
        model4.setRowCount(0);
        
        ReadFiles("C:\\Users\\chiaj\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\password.txt");
 

    }//GEN-LAST:event_JBShowUserActionPerformed

    private void JBsaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JBsaveActionPerformed
    {//GEN-HEADEREND:event_JBsaveActionPerformed
         //write to password
        
       WriteFiles("C:\\Users\\chiaj\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\password.txt",true);
        
        //write to student credit
      WriteFiles("C:\\Users\\chiaj\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\credit.txt",true);
      
       DefaultTableModel model3 = (DefaultTableModel) JTPasswordTable.getModel();
        model3.setRowCount(0);
      
    }//GEN-LAST:event_JBsaveActionPerformed

    private void JBClearUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JBClearUserActionPerformed
    {//GEN-HEADEREND:event_JBClearUserActionPerformed
        DefaultTableModel model3 = (DefaultTableModel) JTPasswordTable.getModel();
        model3.setRowCount(0);
    }//GEN-LAST:event_JBClearUserActionPerformed

    
    public static void main(String args[])
    {
      
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Register().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBClearUser;
    private javax.swing.JButton JBRegisterUser;
    private javax.swing.JButton JBShowUser;
    private javax.swing.JButton JBUpdateUser;
    private javax.swing.JButton JBsave;
    private javax.swing.JTextField JTFIDReg;
    private javax.swing.JTextField JTFPasswordReg;
    private javax.swing.JTable JTPasswordTable;
    private javax.swing.JLabel RFLabel;
    private javax.swing.JButton jBDeleteUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFNameRegister;
    // End of variables declaration//GEN-END:variables
}
