/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javagrpassignment;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baigs
 */
public class OrderApproved_Vendor extends javax.swing.JFrame {
    private static String userID; 
    /**
     * Creates new form OrderApproved_Vendor
     */
    public OrderApproved_Vendor(String userID) {
        initComponents();
        this.setTitle("Order Status Update");
        setLocationRelativeTo(null);
        this.userID = userID;
        loadOrderData();
    }
    
    
    private void loadOrderData() {
        try (BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\Yanaal\\Documents\\NetBeansProjects\\javagrpassignment\\src\\javagrpassignment\\placed_order.txt"))) {
            DefaultTableModel model = (DefaultTableModel) VOrderStatusTable.getModel();
            model.setRowCount(0);

            String line;
            while ((line = reader.readLine()) != null) {
                String[] columns = line.split(", ");
                
                if (columns.length == 3) {
                line += ", ";  
                columns = line.split(", ");
            }
                if (columns.length >= 4 && columns[0].equals(userID)) {
                model.addRow(columns);
            }        
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading order data.");
        }
    }

    private void updateStatus(String status) {
        int selectedRow = VOrderStatusTable.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) VOrderStatusTable.getModel();
            model.setValueAt(status, selectedRow, 3); // Status is at index 3

            updateStatusInFile(selectedRow, status);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
        }
    }

    private void updateStatusInFile(int rowIndex, String status) {
    File originalFile = new File("C:\\Users\\Yanaal\\Documents\\NetBeansProjects\\javagrpassignment\\src\\javagrpassignment\\placed_order.txt");
    File tempFile = new File("C:\\Users\\Yanaal\\Documents\\NetBeansProjects\\javagrpassignment\\src\\javagrpassignment\\placed_order_temp.txt");

    try (BufferedReader reader = new BufferedReader(new FileReader(originalFile));
         BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {

        String line;
        int count = 0;

        while ((line = reader.readLine()) != null) {
            if (count == rowIndex) {
                String[] columns = line.split(", ");
                if (columns.length < 4) {
                    String[] newColumns = new String[4];
                    System.arraycopy(columns, 0, newColumns, 0, columns.length);
                    columns = newColumns;
                }
                columns[3] = status;
                line = String.join(", ", columns);
            }
            writer.write(line);
            writer.newLine();
            count++;
        }

    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error updating status in file.");
        return;
    }

    if (!originalFile.delete()) {
        JOptionPane.showMessageDialog(this, "Error deleting the original file.");
        return;
    }

    if (!tempFile.renameTo(originalFile)) {
        JOptionPane.showMessageDialog(this, "Error renaming the temporary file.");
        return;
    }

    loadOrderData();
    JOptionPane.showMessageDialog(this, "Status updated successfully!");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rejectbtn = new javax.swing.JButton();
        Approvebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        VOrderStatusTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Rejectbtn.setText("Reject");
        Rejectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectbtnActionPerformed(evt);
            }
        });

        Approvebtn.setText("Approve");
        Approvebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApprovebtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Approve/Reject Order");

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        VOrderStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "VendorID", "Food Name", "Price", "Status"
            }
        ));
        jScrollPane2.setViewportView(VOrderStatusTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Rejectbtn)
                .addGap(18, 18, 18)
                .addComponent(Approvebtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Rejectbtn)
                        .addComponent(Approvebtn)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RejectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectbtnActionPerformed
        // TODO add your handling code here:
        updateStatus("Rejected");
    }//GEN-LAST:event_RejectbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        VendorOrderDetails page8 = new VendorOrderDetails(userID);
        page8.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ApprovebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApprovebtnActionPerformed
        // TODO add your handling code here:
        updateStatus("Approved");
    }//GEN-LAST:event_ApprovebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderApproved_Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderApproved_Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderApproved_Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderApproved_Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderApproved_Vendor(userID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Approvebtn;
    private javax.swing.JButton Rejectbtn;
    private javax.swing.JTable VOrderStatusTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
