/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javagrpassignment;

import java.io.*;
import javagrpassignment.VendorOrderDetails;
import javax.swing.JLabel;

/**
 *
 * @author Yanaal
 */
public class VendorPage extends javax.swing.JFrame {
    private String userID;
 
    public VendorPage(String userID) {
        initComponents();
        this.setTitle("Home Page");
        setLocationRelativeTo(null);
        this.userID = userID;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Vendorlbl = new javax.swing.JLabel();
        VOrderbtn = new javax.swing.JButton();
        VMenubtn = new javax.swing.JButton();
        VLogOutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        Vendorlbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Vendorlbl.setText("Vendor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Vendorlbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Vendorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        VOrderbtn.setText("Accept/Cancel Order");
        VOrderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOrderbtnActionPerformed(evt);
            }
        });

        VMenubtn.setText("Menu Management");
        VMenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VMenubtnActionPerformed(evt);
            }
        });

        VLogOutbtn.setText("Log Out");
        VLogOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VLogOutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(VLogOutbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VOrderbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VMenubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(VOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VMenubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(VLogOutbtn)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VOrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOrderbtnActionPerformed
        // Open VendorOrerDetails
        VendorOrderDetails page2 = new VendorOrderDetails(userID);
        page2.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_VOrderbtnActionPerformed

    private void VMenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VMenubtnActionPerformed
        // TODO add your handling code here:
              
        VendorMenu page3 = new VendorMenu(userID);
        page3.setVisible(true);
        this.setVisible(false);
    }
      private void createMenuFile() {
        File file = new File("C:\\Users\\baigs\\OneDrive\\Documents\\NetBeansProjects\\JavaGrpAssignment\\src\\javagrpassignment/menu_details.txt");

        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        
          // Assuming vendor details are stored in another file
        File vendorDetailsFile = new File("C:\\Users\\baigs\\OneDrive\\Documents\\NetBeansProjects\\JavaGrpAssignment\\src\\javagrpassignment\\password.txt");

        try (FileReader fr = new FileReader(vendorDetailsFile);
             BufferedReader br = new BufferedReader(fr);
             FileWriter writer = new FileWriter(file)) {

            String line;
            while ((line = br.readLine()) != null) {
                String[] vendorDetails = line.split(", "); 

                writer.write(vendorDetails[1] + "\t"); // Vendor ID
                writer.write(vendorDetails[0] + "\t"); // Vendor Name

                writer.write("YourStringValue" + "\t");

                writer.write("123" + "\n"); 
            }
        }catch (IOException e) {
        e.printStackTrace();
        
        }
    }//GEN-LAST:event_VMenubtnActionPerformed

    private void VLogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VLogOutbtnActionPerformed
        // TODO add your handling code here:
        Login a =new Login();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VLogOutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(VendorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(VendorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(VendorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(VendorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
 java.awt.EventQueue.invokeLater(() -> {

    Login login = new Login();
    login.setVisible(true);

    String loggedInUserID = login.getLoggedInUserID();
   
    VendorPage vendorPage = new VendorPage(loggedInUserID);
    vendorPage.setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VLogOutbtn;
    private javax.swing.JButton VMenubtn;
    private javax.swing.JButton VOrderbtn;
    private javax.swing.JLabel Vendorlbl;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
